// backend/src/types/ExerciseFrequency.ts
export enum ExerciseFrequency {
  NOT_SPECIFIED = 'NOT_SPECIFIED',
  ONCE_A_WEEK = 'ONCE_A_WEEK',
  TWICE_A_WEEK = 'TWICE_A_WEEK',
  THREE_TIMES_A_WEEK = 'THREE_TIMES_A_WEEK',
  FOUR_TIMES_A_WEEK = 'FOUR_TIMES_A_WEEK',
  FIVE_TIMES_A_WEEK = 'FIVE_TIMES_A_WEEK',
  SIX_TIMES_A_WEEK = 'SIX_TIMES_A_WEEK',
  EVERY_DAY = 'EVERY_DAY',
}
