export interface MealPlan {
  /**
   * Unique identifier for the user this plan belongs to.
   * e.g. 'U123'
   */
  userId: string;

  /**
   * Unique identifier for this meal plan, e.g. 'MP789'.
   * Could be generated by the system.
   */
  mealPlanId: string;

  /**
   * Full meal plan data in JSON format.
   * The structure can vary based on your LLM’s output.
   */
  planJson: string;
  // or use a more structured type if your LLM output is consistent
  // planJson: { [day: string]: { [mealType: string]: { ... } } };

  /** Timestamp when the meal plan was created or updated. */
  createdAt: string;
}
